In [2]:
import tensorflow as tf

In [28]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

print(not_shuffled)

for i in range(10):
    shuffled = tf.random.shuffle(not_shuffled)
    print(shuffled)

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 3  4]
 [ 2  5]
 [10  7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [10  7]
 [ 3  4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [ 3  4]
 [10  7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [ 3  4]
 [10  7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[10  7]
 [ 2  5]
 [ 3  4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[10  7]
 [ 2  5]
 [ 3  4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 3  4]
 [ 2  5]
 [10  7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[10  7]
 [ 2  5]
 [ 3  4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [ 3  4]
 [10  7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [10  7]
 [ 3  4]], shape=(3, 2), dtype=int32)


In [29]:
print(tf.random.set_seed(42))
for i in range(10):
    print(tf.random.shuffle(not_shuffled, seed=42))

None
tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [10  7]
 [ 3  4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [10  7]
 [ 3  4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 3  4]
 [ 2  5]
 [10  7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 3  4]
 [ 2  5]
 [10  7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [10  7]
 [ 3  4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [10  7]
 [ 3  4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 3  4]
 [10  7]
 [ 2  5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [10  7]
 [ 3  4]], shape=(3, 2), dtype=int32)


In [1]:
import tensorflow as tf
print(tf.__version__)

2.10.0


In [42]:
var1 = tf.random.Generator.from_seed(42)
var1 = var1.normal(shape=(3,2,2))
var1

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ]],

       [[-0.23193765, -1.8107855 ],
        [ 0.09988727, -0.50998646]],

       [[-0.7535806 , -0.5716629 ],
        [ 0.1480774 , -0.23362991]]], dtype=float32)>

In [52]:
print(tf.random.shuffle(var1))

tf.Tensor(
[[[-0.7535806  -0.5716629 ]
  [ 0.1480774  -0.23362991]]

 [[-0.23193765 -1.8107855 ]
  [ 0.09988727 -0.50998646]]

 [[-0.7565803  -0.06854702]
  [ 0.07595026 -1.2573844 ]]], shape=(3, 2, 2), dtype=float32)


Create ones, zeros

In [57]:
print(tf.ones(shape=(3,2)))
print(tf.zeros(shape=(3,2)))

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [75]:
import numpy as np
a = np.arange(1, 25)
print(a)
A = tf.constant(a)
print(A)
print(A.ndim)
B = tf.constant(A, shape=(3, 8))
print(B)
print(B.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)
1
tf.Tensor(
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]], shape=(3, 8), dtype=int32)
2


In [69]:
print(tf.random.shuffle(B))

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


In [92]:
sca = tf.constant(7)
print(sca)
vector = tf.constant([1,2,3])
print(vector)
matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
tensor = tf.constant([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(tensor.ndim)
tensor4 = tf.ones(shape=(2,3,4,5))
tensor4

tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
3


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [94]:
print(tensor4.ndim, tensor4.shape, tf.size(tensor4))

4 (2, 3, 4, 5) tf.Tensor(120, shape=(), dtype=int32)


In [100]:
tensor2 = tf.constant([[10, 7],[3, 4]])
tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [101]:
tensor2[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [102]:
tensor3 = tensor2[..., tf.newaxis]
tensor3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [108]:
tensor = tf.constant([[10, 7],[3, 4]])
tensor, tensor[0]+ 10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 17])>)

In [110]:
tensor2
print(tf.linalg.matmul(tensor, tensor2))

tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)


In [123]:
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
print(x)
print(x.shape)
y = tf.constant(x)
print(y)
print(tf.reshape(y, shape=(3,2)))
print(tf.transpose(y))

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
(3, 2)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)


In [125]:
print("Normal Y:", y)
print("Transpose Y:", tf.transpose(y))
print("Reshape Y:", tf.reshape(y, shape=(2,3)))

Normal Y: tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Transpose Y: tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)
Reshape Y: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [132]:
C = tf.constant([1,2.5,3])
C


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1. , 2.5, 3. ], dtype=float32)>

In [134]:
D = tf.cast(C, dtype=tf.float16)
D

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1. , 2.5, 3. ], dtype=float16)>

In [3]:
E = tf.random.Generator.from_seed(42)
E = E.normal(shape=(100,100))
E

<tf.Tensor: shape=(100, 100), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, ..., -0.3741098 ,
        -0.28709963,  1.5089895 ],
       [-0.14833727, -1.2846565 ,  0.5484313 , ...,  0.0044825 ,
         0.16218606, -2.2107327 ],
       [-0.897285  ,  1.17089   , -0.70234615, ..., -1.0718341 ,
        -1.0722276 , -0.00586287],
       ...,
       [-0.04875139,  0.4720202 , -0.1468142 , ..., -0.16058625,
         0.30491093, -0.08115519],
       [ 1.4559728 ,  0.702725  , -0.49598402, ..., -0.5274568 ,
         0.50659525,  0.35393006],
       [-0.9073771 ,  1.9859369 , -0.12666915, ...,  0.5728476 ,
        -0.7579853 , -0.10818893]], dtype=float32)>

In [2]:
import tensorflow as tf
E = tf.random.Generator.from_seed(42)
E = E.normal(shape=(100,100))
print(tf.math.reduce_variance(E))

tf.Tensor(0.97676873, shape=(), dtype=float32)


In [6]:
F= tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [11]:
print(tf.argmax(F))
print(F[tf.argmax(F)])

tf.Tensor(42, shape=(), dtype=int64)
tf.Tensor(0.9671384, shape=(), dtype=float32)


In [14]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [18]:
G.ndim, G.ndim

(5, 5)

In [22]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [31]:
somelist = [0,1,2,3]
tf.one_hot(somelist, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [33]:
tf.one_hot(somelist, depth=4, on_value='On', off_value='Off')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'On', b'Off', b'Off', b'Off'],
       [b'Off', b'On', b'Off', b'Off'],
       [b'Off', b'Off', b'On', b'Off'],
       [b'Off', b'Off', b'Off', b'On']], dtype=object)>

In [37]:
H = tf.range(1, 10)
print(tf.square(H))
H

tf.Tensor([ 1  4  9 16 25 36 49 64 81], shape=(9,), dtype=int32)


<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [40]:
import numpy as np
J = tf.constant(np.array([1,2,3,4]))
J

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [42]:
type(J)
type(J.numpy())

numpy.ndarray

EXERCISE

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
vector = tf.constant(10)
print(vector)
scalar = tf.constant([10, 20, 30])
print(scalar)
matrix = tf.constant([[10, 20],
                      [30, 40]])
print(matrix)
tensor = tf.constant([[[10],[20]],[[30],[40]]])
print(tensor)

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor([10 20 30], shape=(3,), dtype=int32)
tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[10]
  [20]]

 [[30]
  [40]]], shape=(2, 2, 1), dtype=int32)


In [4]:
print(vector.shape, vector.ndim, tf.size(vector))
print(scalar.shape, scalar.ndim, tf.size(scalar))
print(matrix.shape, matrix.ndim, tf.size(matrix))
print(tensor.shape, tensor.ndim, tf.size(tensor))

() 0 tf.Tensor(1, shape=(), dtype=int32)
(3,) 1 tf.Tensor(3, shape=(), dtype=int32)
(2, 2) 2 tf.Tensor(4, shape=(), dtype=int32)
(2, 2, 1) 3 tf.Tensor(4, shape=(), dtype=int32)


In [13]:
tensor1 = tf.random.uniform(shape=(5, 300))
tensor1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.25582302, 0.85153854, 0.6300348 , ..., 0.85241103, 0.47931814,
        0.29273927],
       [0.1918323 , 0.6157763 , 0.4505397 , ..., 0.04304302, 0.5402771 ,
        0.7534255 ],
       [0.9456587 , 0.9493699 , 0.13307011, ..., 0.18224645, 0.50680923,
        0.73411083],
       [0.57366514, 0.445521  , 0.01820827, ..., 0.6891072 , 0.14001143,
        0.12638724],
       [0.08435595, 0.51331687, 0.7013862 , ..., 0.6301166 , 0.86020017,
        0.93512106]], dtype=float32)>

In [14]:
tensor2 = tf.random.uniform(shape=(5,300))
tensor2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.37020636, 0.37435293, 0.0816654 , ..., 0.8290738 , 0.96353793,
        0.6271162 ],
       [0.9262465 , 0.13570356, 0.66506743, ..., 0.9753077 , 0.2603302 ,
        0.47416532],
       [0.30618548, 0.17960238, 0.35634768, ..., 0.19133627, 0.04732323,
        0.71456397],
       [0.17287433, 0.8388939 , 0.58046186, ..., 0.7330228 , 0.5733161 ,
        0.0555861 ],
       [0.6329119 , 0.39002848, 0.7403214 , ..., 0.98115385, 0.7590109 ,
        0.48232973]], dtype=float32)>

In [16]:
mul = tf.matmul(tensor1, tf.transpose(tensor2))
mul

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[74.17111 , 80.705826, 76.655075, 76.45989 , 75.846855],
       [76.22114 , 77.24733 , 74.64158 , 76.81625 , 73.66083 ],
       [71.56465 , 71.79433 , 71.14218 , 72.719185, 71.63349 ],
       [74.33443 , 78.89995 , 73.11275 , 76.242805, 76.24185 ],
       [75.68113 , 74.65414 , 70.2192  , 71.520615, 72.71155 ]],
      dtype=float32)>

In [18]:
mul2 = tf.tensordot(tensor1, tf.transpose(tensor2), axes=1)
mul2

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[74.17111 , 80.705826, 76.655075, 76.45989 , 75.846855],
       [76.22114 , 77.24733 , 74.64158 , 76.81625 , 73.66083 ],
       [71.56465 , 71.79433 , 71.14218 , 72.719185, 71.63349 ],
       [74.33443 , 78.89995 , 73.11275 , 76.242805, 76.24185 ],
       [75.68113 , 74.65414 , 70.2192  , 71.520615, 72.71155 ]],
      dtype=float32)>